version: '3.2'
services:
  database:
    image: 'mysql:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=springBoot
      - MYSQL_DATABASE=spring_init_demo
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
    networks:
      - spring-boot-mysql-network
    volumes:
      - 'db-data:/var/lib/mysql'
    ports:
      - '3306:3306/tcp'
    expose:
      - 3306
  webservices:
    build:
      context: ./../
      dockerfile: docker/backend/Dockerfile
    expose:
      - 4000
    depends_on:
      - database
    networks:
      - spring-boot-mysql-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/spring_init_demo?serverTimezone=CST&useLegacyDatetimeCode=false
      - SPRING_DATASOURCE_USERNAME=springuser
      - SPRING_DATASOURCE_PASSWORD=ThePassword
networks:
  spring-boot-mysql-network:
    driver: bridge
volumes:
  db-data: null
